services:
  wordpress:
    image: wordpress:php8.3-apache
    ports:
      - "80:80"
    volumes:
      - ./data/html:/var/www/html
      - type: bind
        source: "./configs/php/php.ini"
        target: "/usr/local/etc/php/php.ini"
      - type: bind
        source: "./configs/apache/apache.conf"
        target: "/etc/apache2/conf-enabled/gentle-blog.conf"
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: "{MYSQL_DATABASE}"
      WORDPRESS_DB_USER: "{MYSQL_USER}"
      WORDPRESS_DB_PASSWORD: "{MYSQL_PASSWORD}"
      WORDPRESS_TABLE_PREFIX: "wp_"
      WORDPRESS_DEBUG: 0

  mysql:
    image: mariadb:11
    # ports:
      # - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: "{MYSQL_ROOT_PASSWORD}"
      MARIADB_DATABASE: "{MYSQL_DATABASE}"
      MARIADB_USER: "{MYSQL_USER}"
      MARIADB_PASSWORD: "{MYSQL_PASSWORD}"
    volumes:
      - ./data/mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "127.0.0.1:8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: "{MYSQL_ROOT_PASSWORD}"